---
- name: Install mysql
  sudo: true
  apt: 
    name: "{{ item }}" 
    state: present
  with_items:
    - mysql-server
    - python-mysqldb
    - php5-mysql

- name: Setup root user password
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_pass }}"
    login_user: root
    login_password: "{{ mysql_root_pass }}"
    check_implicit_admin: true
    priv: "*.*:ALL,GRANT"
  with_items:
    - localhost
    - 127.0.0.1
    - ::1
    - "{{ ansible_hostname }}"
