# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "cargomedia/debian-7-amd64-plain"
	config.vm.synced_folder ".", "/vagrant", type: "nfs"
	# Note swith nfs to smb on Windows host
	# If client is remote (eg AWS) consider having type rsync
	config.vm.provider "virtualbox" do |v|
		v.name = "lamp3" # Change the name here to something unique!
		v.memory = 512
		v.cpus = 2
	end

	config.vm.hostname = "lamp3"
  config.vm.network "private_network", ip: "192.168.33.14"
  config.vm.network "forwarded_port", guest: 80, host: 8083

	# Set the name of the VM
	config.vm.define :lamp3 do |lamp3|
	end

	config.vm.provision "ansible" do |ansible|
		ansible.playbook = "ansible/playbook.yml"
		ansible.sudo = true
	end

end
