---
- name: Install apache
  apt: name=apache2 state=present
- name: New vhost config
  template: 
    src=vhost.conf.j2
    dest=/etc/apache2/sites-available/vhost.conf
  notify:
    - Reload apache
- name: Remove default vhost file
  file:
    path=/etc/apache2/sites-enabled/000-default
    state=absent
  notify:
    - Reload apache
- name: Enable new vhost
  file:
    src=/etc/apache2/sites-available/vhost.conf
    dest=/etc/apache2/sites-enabled/000-vhost.conf
    state=link
  notify:
    - Reload apache
